---
kind: pipeline
name: default
type: docker

steps:
- name: nextcloud stable
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: stable
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=stable-fpm-alpine

- name: nextcloud latest
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: latest
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=fpm-alpine

- name: nextcloud 30
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 30
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=30-fpm-alpine

- name: nextcloud 31
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 31
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=31-fpm-alpine

- name: nextcloud 32
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 32
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=32-fpm-alpine

- name: nextcloud 33
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 33
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=33-fpm-alpine

- name: nextcloud 34
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    repo: yavook/kiwi-nextcloud
    tags: 34
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    build_args:
      - NC_VERSION=34-fpm-alpine

- name: parallelism provider
  image: alpine
  depends_on:
    - nextcloud stable
    - nextcloud latest
    - nextcloud 30
    - nextcloud 31
    - nextcloud 32
    - nextcloud 33
    - nextcloud 34
